name: Deploy to GCS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: data-engineering-prep-466112

      - name: Save GCP credentials
        run: echo "${{ secrets.GCP_SA_KEY }}" > $HOME/gcp-key.json

      - name: Authenticate with gcloud
        run: gcloud auth activate-service-account --key-file=$HOME/gcp-key.json

      - name: Copy files to GCS bucket
        run: |
          gsutil -m rsync -r ./ gs://gcp-workflow-dags-df/

