name: Deploy to GCS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Decode and save GCP service account key
        run: |
          echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 --decode > $HOME/gcp-key.json

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ steps.decode-sa-key.outputs.key_file }}
          project_id: your-gcp-project-id

      - name: Copy files to GCS bucket
        run: |
          gsutil -m rsync -r ./dags gs://your-gcs-bucket-name/


