name: Deploy to GCS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Decode and save GCP service account key
        run: |
          echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 --decode > $HOME/gcp-key.json

      - name: Authenticate with GCP
        run: gcloud auth activate-service-account --key-file=$HOME/gcp-key.json

      - name: Set GCP project
        run: gcloud config set project data-engineering-prep-466112

      - name: Install yq (YAML parser)
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Read paths to deploy from script_execution_order.yaml
        id: get_paths
        run: |
          paths=$(yq e '.paths_to_deploy[]' script_execution_order.yaml | paste -sd ' ')
          echo "paths=$paths" >> $GITHUB_OUTPUT

      - name: Sync specified paths to GCS bucket
        run: |
          for path in ${{ steps.get_paths.outputs.paths }}
          do
            echo "Syncing $path to gs://gcp-workflow-dags-df/$path"
            gsutil -m rsync -r "$path" "gs://gcp-workflow-dags-df/$path"
          done



