name: Deploy to GCS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Decode and save GCP service account key
        run: |
          echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 --decode > $HOME/gcp-key.json

      - name: Authenticate with GCP
        run: gcloud auth activate-service-account --key-file=$HOME/gcp-key.json

      - name: Set GCP project
        run: gcloud config set project data-engineering-prep-466112

      - name: Copy files to GCS bucket
        run: gsutil -m rsync -r ./ gs://gcp-workflow-dags-df/


